# Generated by Django 5.0 on 2024-01-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ver_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='код варификации'),
        ),
    ]
