# Generated by Django 5.0 on 2024-01-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_logmailing_status_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmailing',
            name='date_try',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя попытка'),
        ),
        migrations.AlterField(
            model_name='logmailing',
            name='status_try',
            field=models.CharField(blank=True, default='Попытки не было', max_length=25, null=True, verbose_name='статус попытки'),
        ),
    ]
